function Plot_DDM_data()
% Plots data generated by the Perform_simulation_DDM script
% Requires the simulated participant data to be present in
% DDM_scripts\Output
% Opens the plots, and saves them to DDM_scripts\Output_plots
% Generates a plot for the simulated dACC activity, boost activity and
% value activity. Additionally, generates a comparison with the 


cd('DDM_RML')
addpath('Functions')
loc = fullfile('Output'); % Location of analysed participant data
nparts = 200; % Number of simulated participants
fulldat = {};

for part = 1:nparts % Load data from simulations
    load(fullfile(loc,strcat('DDM_S',num2str(part),'.mat')))
    fulldat{part}=dat;
end
savename = 'Output_plots';
second_level_an_ho2_DDM(fulldat,savename) % Perform analysis and plot data
Plot_acc_RT_fit(); % Fit the accuracy and RT to the original data from Vassena et al.
Plot_surprise(); % Plots the surprise figure
rmpath('Functions')
rmpath('.')
cd('..')
end