function dat = store_single_trial_info(dat,dat_single_trial,trial)
% Function appending the data generated by Perform_RML to dat

nstatesvisited = length(dat_single_trial.state);

% Check if this number of states has ever been visited before
if isempty(dat)
    dat.state(1:trial-1,:) = NaN;
    dat.action(1:trial-1,:) = NaN;
    dat.boost(1:trial-1,:) = NaN;
    dat.V(1:trial-1,:) = NaN;
    dat.V2(1:trial-1,:) = NaN;
    dat.value_1(1:trial-1,:) = NaN;
    dat.value_2(1:trial-1,:) = NaN;
    dat.RW(1:trial-1,:)=NaN;
    dat.RT(1:trial-1,:)=NaN;
    dat.VTA(1:trial-1,:)=NaN;
    dat.VTA_boost(1:trial-1,:)=NaN;
else
    maxstatesvisited = size(dat.state,2);
    if maxstatesvisited<nstatesvisited
        % Add nans to the end of each previous trial
        dat.state(:,maxstatesvisited+1:nstatesvisited) = NaN;
        dat.action(:,maxstatesvisited+1:nstatesvisited) = NaN;
        dat.boost(:,maxstatesvisited+1:nstatesvisited) = NaN;
        dat.V(:,maxstatesvisited+1:nstatesvisited) = NaN;
        dat.V2(:,maxstatesvisited+1:nstatesvisited) = NaN;
        dat.value_1(:,maxstatesvisited+1:nstatesvisited) = NaN;
        dat.value_2(:,maxstatesvisited+1:nstatesvisited) = NaN;
        dat.RW(:,maxstatesvisited+1:nstatesvisited)=NaN;
        dat.RT(:,maxstatesvisited+1:nstatesvisited)=NaN;
        dat.VTA(:,maxstatesvisited+1:nstatesvisited)=NaN;
        dat.VTA_boost(:,maxstatesvisited+1:nstatesvisited)=NaN;
    else
        dat.state(trial,:) = NaN;
        dat.action(trial,:) = NaN;
        dat.boost(trial,:) = NaN;
        dat.V(trial,:) = NaN;
        dat.V2(trial,:) = NaN;
        dat.value_1(trial,:) = NaN;
        dat.value_2(trial,:) = NaN;
        dat.RW(trial,:)=NaN;
        dat.RT(trial,:)=NaN;
        dat.VTA(trial,:)=NaN;
        dat.VTA_boost(trial,:)=NaN;
    end
end

dat.state(trial,1:nstatesvisited) = dat_single_trial.state;
dat.action(trial,1:nstatesvisited) = dat_single_trial.action;
dat.boost(trial,1:nstatesvisited) = dat_single_trial.boost;
dat.V(trial,1:nstatesvisited) = dat_single_trial.Vpre;
dat.V2(trial,1:nstatesvisited) = dat_single_trial.V2pre;
dat.value_1(trial,1:nstatesvisited) = dat_single_trial.value_1;
dat.value_2(trial,1:nstatesvisited) = dat_single_trial.value_2;
dat.RW(trial,1:nstatesvisited)=dat_single_trial.RW;
dat.RT(trial,1:nstatesvisited)=dat_single_trial.RT;

dat.VTA(trial,1:nstatesvisited)=dat_single_trial.VTA;
dat.VTA_boost(trial,1:nstatesvisited)=dat_single_trial.VTA_boost;

end